### ISSUE TITLE
need little help with task definition

### ISSUE THREAD

**Issue by simonfloris** [gulpsome/gulp-harp#1]
I did the following , call your wrapper with  current gulp as first parameter harcoded options as second.
I get the following error:

Error: Task harp can't support dependencies that is not an array of strings

Could you advise how to get this running, sourcemap is a deeply missed feature for our team.

```
import gulpHarp from 'gulp-harp';
/**
 * Serve the Harp Site from the app directory
 */
gulp.task('serve', function () {
  gulpHarp(gulp, {
    "harp": {
      "path": "app/",
      "name": "harp",
      "help": "Harp server",
      "port": 9000
    },
    "harp-sync": {
      "help": "Harp server & browser-sync",
      "sync": {
        "options": {
          "proxy": "localhost:9000",
          "open": false,
          "notify": false
        }
      }
    }
  })
});
```

**Comment by orlin** [comment]
Sorry it took so long to notice your question!  I see `index.json` mislead you to use it straight as options -- that's internal defaults separating harp options from browser-sync options.  I should have added some documentation long ago...  There's a usage example on the readme now.  With options as they are expected.  Please note that the task is automatically added for you when you give `gulpHarp` a `gulp`.  There is now a link on the readme to a site that's using gulp-harp, though through a [beverage](https://github.com/gulpsome/beverage).  I believe you will find that even more satisfying.  Closing the issue, though feel free to reopen if this hasn't solved it.
